name: Build SunamoDebugCollection

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoDebugCollection
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoDebugCollection/SunamoDebugCollection.csproj

    - name: Build
      run: dotnet build SunamoDebugCollection/SunamoDebugCollection.csproj --configuration Release --no-restore

  test:
    name: Test SunamoDebugCollection.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoDebugCollection.Tests/SunamoDebugCollection.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoDebugCollection.Tests/SunamoDebugCollection.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoDebugCollection.Tests/SunamoDebugCollection.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
